mojohaus/extra-enforcer-rules

src/main/java/org/apache/maven/plugins/enforcer/RequireEncoding.java
src/site/apt/requireEncoding.apt.vm

Small typo in the documentation. Name of property in code is correct.

Fix spelling of project.build.sourceEncoding in documentation

---

pom.xml
src/it/enforce-bytecode-version-with-corrupted-jar/invoker.properties
src/it/enforce-bytecode-version-with-corrupted-jar/pom.xml
src/it/enforce-bytecode-version-with-corrupted-jar/setup.groovy
src/it/enforce-bytecode-version-with-corrupted-jar/verify.groovy
src/main/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersion.java

if you have a corrupted jar for a dependency somewhere in a local repo,
the rule just issued a NPE with no hint on which file had a problem.
```
Caused by: java.lang.NullPointerException: null
at org.apache.maven.plugins.enforcer.EnforceBytecodeVersion.isBadArtifact(EnforceBytecodeVersion.java:311) ~[na:na]
at org.apache.maven.plugins.enforcer.EnforceBytecodeVersion.checkDependencies(EnforceBytecodeVersion.java:220) ~[na:na]
at org.apache.maven.plugins.enforcer.EnforceBytecodeVersion.handleArtifacts(EnforceBytecodeVersion.java:146) ~[na:na]
at org.apache.maven.plugins.enforcer.AbstractResolveDependencies.execute(AbstractResolveDependencies.java:77) ~[na:na]
at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:193) ~[na:na]
at …
```

Handle corrupted jars in EnforceBytecodeVersion

---

src/main/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersion.java

Similarly to @Vlatombe’s #27, @kshultzCB reported an error which with `-e` displayed a root cause:
```
java.lang.IllegalArgumentException: MALFORMED
at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
at java.util.zip.ZipFile.getZipEntry(ZipFile.java:583)
at java.util.zip.ZipFile.access$900(ZipFile.java:60)
at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:539)
at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:514)
at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
at java.util.jar.JarFile$JarEntryIterator.next(JarFile.java:257)
at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:266)
at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:247)
at org.apache.maven.plugins.enforcer.EnforceBytecodeVersion.isBadArtifac …
```

JarFile$JarEntryIterator.nextElement can throw IllegalArgumentException

---

pom.xml
src/it/banduplicate-classes-fail-when-not-identical/invoker.properties
src/it/banduplicate-classes-fail-when-not-identical/pom.xml
src/it/banduplicate-classes-fail-when-not-identical/verify.groovy
src/it/banduplicate-classes-ignore-when-identical/invoker.properties
src/it/banduplicate-classes-ignore-when-identical/pom.xml
src/it/banduplicate-classes-ignore-when-identical/verify.groovy
src/main/java/org/apache/maven/plugins/enforcer/BanDuplicateClasses.java
src/main/java/org/apache/maven/plugins/enforcer/ClassFile.java
src/main/java/org/apache/maven/plugins/enforcer/ClassesWithSameName.java
src/main/java/org/apache/maven/plugins/enforcer/Hasher.java
src/main/java/org/apache/maven/plugins/enforcer/JarUtils.java
src/site/apt/banDuplicateClasses.apt.vm
src/test/java/org/apache/maven/plugins/enforcer/ArtifactBuilder.java
src/test/java/org/apache/maven/plugins/enforcer/ClassFileHelper.java
src/test/java/org/apache/maven/plugins/enforcer/ClassFileTest.java
src/test/java/org/apache/maven/plugins/enforcer/ClassesWithSameNameTest.java
src/test/java/org/apache/maven/plugins/enforcer/HasherTest.java
src/test/java/org/apache/maven/plugins/enforcer/JarUtilsTest.java

I realize this is a commit bomb, but it adds a new feature to BanDuplicateClasses and lots of tests.
Explanation:
If we have two classes with the same fully qualified name on the classpath BanDuplicateClasses fails, but with this enhancement it only fails if the bytecode of those class files differs. In other words, if they're an exact binary match we skip the classes and move on. The idea being: there's technically no problem if they're the same exact file. This also means there's potentially less fixes to make when porting a large pom.xml to start using BanDuplicateClasses for the first time.
But most importantly: with this new option enabled any time BanDuplicateClasses fails it means there is a definite classpath problem, 100% of the time.
The new option is off by default, but can be …

let BanDuplicateClasses ignore when the bytecode matches exactly

---

.travis.yml
appveyor.yml
pom.xml
src/it/compiling/pom.xml
src/it/enforce-bytecode-version-with-corrupted-jar/verify.groovy
src/main/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersion.java
src/site/apt/enforceBytecodeVersion.apt.vm
src/test/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersionTest.java

Fixes #61 
Travis CI tests with cobertura reports failed with Java 11 due to not existing tools.jar - probably this plugin should be excluded from the build.

Add support for Java 11 and test with Maven 3.6.0

---

src/main/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersion.java

JDK 12 is already expected in next March, per https://openjdk.java.net/projects/jdk/12/
So let's "support" it rather sooner than later.
Following up on @oleg-nenashev comment in https://github.com/mojohaus/extra-enforcer-rules/pull/63

Add Java 12 major version number

---

appveyor.yml
pom.xml

Simplify build configuration and use default Maven version (3.6) installed on AppVeyor workers
Fixes problem with connection to Central (TLS1.2)
This PR build status: [![build status](https://ci.appveyor.com/api/projects/status/r0f8kk0qg0yjcdhe?svg=true&1)](https://ci.appveyor.com/project/slachiewicz/extra-enforcer-rules)
Master branch status: [![Build Status (for master branch)](https://ci.appveyor.com/api/projects/status/github/mojohaus/extra-enforcer-rules?branch=master&svg=true)](https://ci.appveyor.com/project/khmarbaise/extra-enforcer-rules)

Correct AppVeyor build for Java 7 and 11

---

src/main/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersion.java
src/test/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersionTest.java

Small followup on #63 and #64 
Despite https://openjdk.java.net/jeps/223 officially deprecating 1.x schemes, we should be permissive here to avoid crashes.
For instance, in Jenkins the version in use is `1.${java.level}`.
https://github.com/jenkinsci/plugin-pom/blob/master/pom.xml#L522
So supporting both formats will avoid unnecessary headaches around. We'll see possibly in the future to stop supporting this when the oldest line is >=9 and no more 1.x format can exist.
cc @jenkinsci/java11-support

Also support 1.x version schemes

---

src/it/enforce-bytecode-version-module-info-jdk8/invoker.properties
src/it/enforce-bytecode-version-module-info-jdk8/pom.xml
src/it/enforce-bytecode-version-module-info-jdk8/verify.groovy
src/it/enforce-bytecode-version-module-info-jdk9/invoker.properties
src/it/enforce-bytecode-version-module-info-jdk9/pom.xml
src/it/enforce-bytecode-version-module-info-jdk9/verify.groovy
src/main/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersion.java

Context: #46, #36, #75 
Fix from #36 would cause unnecessary noise such as
```
[WARNING] Invalid bytecodeVersion for module-info.class: expected 52, but was 53
[WARNING] Invalid bytecodeVersion for module-info.class: expected 52, but was 53
[WARNING] Invalid bytecodeVersion for module-info.class: expected 52, but was 53
[WARNING] Invalid bytecodeVersion for module-info.class: expected 52, but was 53
[WARNING] Invalid bytecodeVersion for module-info.class: expected 52, but was 53
[WARNING] Invalid bytecodeVersion for module-info.class: expected 52, but was 53
[WARNING] Invalid bytecodeVersion for module-info.class: expected 52, but was 53
```
This supercedes #75.
This fix takes a different approach: when maxJdkVersion < 1.9, `module-info` is just ignored automatically.

Ignore automatically module-info.class when maxJdkVersion < 1.9

---

src/site/apt/index.apt

I think it's now safe to assume no one is using enforcer plugin 1.x and is using a release version of these rules.

Remove note

---

pom.xml
src/it/require-encoding-iso88591/pom.xml
src/it/require-encoding-iso88591/verify.groovy
src/it/require-encoding-usascii/verify.groovy
src/main/java/org/apache/maven/plugins/enforcer/RequireEncoding.java
src/main/java/org/freebsd/file/FileEncoding.java
src/test/java/org/freebsd/file/FileEncodingTest.java

This changes removes the plugin that tried to guess the encoding previous.
Added a java light version of the freebsd file tool encoding guessing implementation. Added acceptAsciiSubset to accept us-ascii as an valid subset for UTF-8 or ISO-8859-1.
This implementation also has support for UTF-8 BOM detection as mentions in issue #25.
Added unit tests för the FileEncoding implementations and updated the it tests when we can detect us-ascii.

Fix for issue #48

---

src/main/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersion.java

15 is in early access.  16 will be soon enough.  Since this looks minimum for the error condition encountered now with 13 and above, this seems appropriate.
This will replace PR #81 and fixes #80.

Add bytecode mapping for Java 13 through 16

---

pom.xml
src/main/java/org/apache/maven/plugins/enforcer/AbstractMojoHausEnforcerRule.java
src/main/java/org/apache/maven/plugins/enforcer/AbstractRequireRoles.java
src/main/java/org/apache/maven/plugins/enforcer/AbstractResolveDependencies.java
src/main/java/org/apache/maven/plugins/enforcer/BanCircularDependencies.java
src/main/java/org/apache/maven/plugins/enforcer/RequireEncoding.java
src/main/java/org/apache/maven/plugins/enforcer/RequireProjectUrl.java
src/main/java/org/apache/maven/plugins/enforcer/RequirePropertyDiverges.java

* Only the old EnforcerRule interface was implemented.
* So the extra-rules could not be set to warn only.
* Although the rules API version is now 1.4.1, using
1.4.1 of the enforcer-plugin is not possible, because
a lot of ITs are failing, then.
Fixes #96

Implement EnforcerRule2 to enable warn level

---

src/it/enforce-bytecode-version-multirelease-2/invoker.properties
src/it/enforce-bytecode-version-multirelease-2/pom.xml
src/it/enforce-bytecode-version-multirelease-2/verify.groovy
src/main/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersion.java

This fixes warnings observed in the jenkins project using this rule.
```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (display-info) @ MY_PROJECT ---
[INFO] Ignoring requireUpperBoundDeps in com.google.guava:guava
[INFO] Adding ignore: module-info
[WARNING] Invalid bytecodeVersion for com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.1:compile : META-INF/versions/11/module-info.class: expected 55, but was 53
```
The check was exact, it should actually be ensuring the bytecode level is lower or equal to what is specified.
Fixes https://github.com/FasterXML/jackson-modules-base/issues/126

Bytecode version of multirelease metadata should be lower or equal to specified version

---

src/main/java/org/apache/maven/plugins/enforcer/RequireEncoding.java

Since ISO-8859-15 is basically ISO-8859-1 plus the Euro-Sign (€), it should be allowed as an ASCII subset:
When project.build.sourceEncoding = ISO-8859-15 and a source file contains no special characters, icu would detect it as ASCII and requireEncoding would fail. This change prevents that.
Also adds an option to allow ISO-8859-15 as a subset of ISO-8859-1.
When project.build.sourceEncoding = ISO-8859-15 and a source file contains special characters but no Euro-Sign, icu would detect the encoding as ISO-8859-1 and requireEncoding would fail. The extra option set to true prevents that.

Allow ISO-8859-15 as subset of ASCII and ISO-8859-1

---

README.md
pom.xml
src/site/apt/banCircularDependencies.apt.vm
src/site/apt/banDuplicateClasses.apt.vm
src/site/apt/enforceBytecodeVersion.apt.vm
src/site/apt/requireContributorRoles.apt.vm
src/site/apt/requireDeveloperRoles.apt.vm
src/site/apt/requireEncoding.apt.vm
src/site/apt/requirePropertyDiverges.apt.vm
src/site/apt/usage.apt.vm
src/site/site.xml
src/test/java/org/codehaus/mojo/extraenforcerrules/it/BanDuplicateClassesLogParser.java

- upgrade parent
- use configuration from parent

Upgrade parent to 68

---

src/main/java/org/apache/maven/plugins/enforcer/AbstractResolveDependencies.java

we should use default remote repositories and repositories defined in project
Fix #225

Use all remote repositories for artifacts resolving

---

src/main/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersion.java
src/test/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersionTest.java

I've verified that this is the only change needed for `EnforceBytecodeVersion` to work properly
Fixes https://github.com/mojohaus/extra-enforcer-rules/issues/261

Recognize JDK 21 class format

---

src/main/java/org/codehaus/mojo/extraenforcer/dependencies/EnforceBytecodeVersion.java
src/test/java/org/codehaus/mojo/extraenforcer/dependencies/EnforceBytecodeVersionTest.java

Consulted with https://javaalmanac.io/bytecode/versions/

Recognize JDK 22-23 class formats

---

src/it/local-project-repo/pom.xml

- project.baseUri is forbidden in  repository.url
- checksum should be ignored

Allow build by Maven 4

---

src/main/java/org/codehaus/mojo/extraenforcer/model/RequirePropertyDiverges.java
src/site/apt/requirePropertyDiverges.apt.vm
src/test/java/org/codehaus/mojo/extraenforcer/model/RequirePropertyDivergesTest.java

Enhancement proposal for rule `requirePropertyDiverges`
As proposed in  #282 to @slawekjaranowski 
Adds a new, optional `<reference>` parameter which can take 3 values:
* DEFINING (current behaviour, default)
* PARENT use direct parent as reference context
* BASE use topmost local POM as reference context
Tests & doc included

Make parent level configurable for reference value in requirePropertyDiverges

---

src/main/java/org/codehaus/mojo/extraenforcer/dependencies/EnforceBytecodeVersion.java
src/test/java/org/codehaus/mojo/extraenforcer/dependencies/EnforceBytecodeVersionTest.java

Class file version as in the: https://github.com/openjdk/jdk/blob/8908812d0a64f25f0d033d44725a69348789b223/src/jdk.compiler/share/classes/com/sun/tools/javac/jvm/ClassFile.java#L131

Recognize JDK 24

---

src/main/java/org/codehaus/mojo/extraenforcer/dependencies/AbstractResolveDependencies.java

Seems null optional fields can exist which causes the rule to crash at runtime since it will try to unbox a null value.
This change helps work around this.
In the case of `MavenArtifact#setOptional`, it accepts a primitive `boolean` value only. The Aether `Dependency#getOptional` method returns a `java.lang.Boolean` which appears to be able to have a null value.
This results in the following crash on Maven 3.9.11, Enforcer rules 1.10.0:
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.6.1:enforce (default) on project xxxxxx: Execution default of goal org.apache.maven.plugins:maven-enforcer-plugin:3.6.1:enforce failed: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of …
```

Update AbstractResolveDependencies.java to handle "null" optional fields
